// import '../../public/app-assets/vendors/js/vendors.min.js'
// import '../../public/app-assets/fonts/LivIconsEvo/js/LivIconsEvo.tools.js'
// import '../../public/app-assets/fonts/LivIconsEvo/js/LivIconsEvo.defaults.js'
// import '../../public/app-assets/fonts/LivIconsEvo/js/LivIconsEvo.min.js'
import '../../public/app-assets/vendors/js/extensions/toastr.min.js'
// import '../../public/app-assets/vendors/js/charts/apexcharts.min.js'
import '../../public/app-assets/vendors/js/extensions/swiper.min.js'
import '../../public/app-assets/js/core/app-menu.js'
import '../../public/app-assets/js/core/app.js'
import '../../public/app-assets/js/scripts/components.js'
import '../../public/app-assets/js/scripts/footer.js'
import '../../public/app-assets/js/scripts/extensions/toastr.js'
// import '../../public/app-assets/js/scripts/pages/dashboard-ecommerce.js'